"""
Type stubs for the native cursor and published-reader classes.

The ``prosody.prosody`` extension module defines these classes, and its stub
re-exports them. A cursor yields the items of one keyed-state scan. A
published reader serves the reads of :mod:`prosody.published`.
"""
from typing import Generic, List, Optional, TypeVar

from prosody.message import JSONValue, Message
from prosody.query import _KeyQuery, _PositionQuery

T = TypeVar("T")
V = TypeVar("V")

class _NativePublishedValue(Generic[T]):
    async def get(self, key: str) -> Optional[T]: ...

class _NativeScan(Generic[T]):
    def __aiter__(self) -> _NativeScan[T]: ...
    async def __anext__(self) -> T: ...
    async def aclose(self) -> None: ...

class NativeJsonDequeScan(_NativeScan[JSONValue]): ...
class NativeJsonMapScan(_NativeScan[tuple[str, JSONValue]]): ...
class NativeMessageDequeScan(_NativeScan[Message[JSONValue]]): ...
class NativeMessageMapScan(_NativeScan[tuple[str, Message[JSONValue]]]): ...
class NativeMapKeyScan(_NativeScan[str]): ...


class _NativePublishedMap(Generic[V]):
    async def get(self, key: str, map_key: str) -> Optional[V]: ...
    async def get_many(self, key: str, map_keys: List[str]) -> List[Optional[V]]: ...
    async def contains_key(self, key: str, map_key: str) -> bool: ...
    async def contains_many(self, key: str, map_keys: List[str]) -> List[bool]: ...
    async def is_empty(self, key: str) -> bool: ...
    def scan(self, key: str, query: _KeyQuery) -> NativeJsonMapScan: ...
    def keys(self, key: str, query: _KeyQuery) -> NativeMapKeyScan: ...


class _NativePublishedSet:
    async def contains(self, key: str, member: str) -> bool: ...
    async def contains_many(self, key: str, members: List[str]) -> List[bool]: ...
    async def is_empty(self, key: str) -> bool: ...
    def keys(self, key: str, query: _KeyQuery) -> NativeMapKeyScan: ...


class _NativePublishedDeque(Generic[T]):
    async def get(self, key: str, index: int) -> Optional[T]: ...
    async def len(self, key: str) -> int: ...
    async def is_empty(self, key: str) -> bool: ...
    async def peek_front(self, key: str) -> Optional[T]: ...
    async def peek_back(self, key: str) -> Optional[T]: ...
    def scan(self, key: str, query: _PositionQuery) -> NativeJsonDequeScan: ...
