from typing import Literal, TypeAlias, TypeVar

T = TypeVar("T", covariant=True)

class ResponseError(Exception): ...

class HandlerResponseError(ResponseError):
    @property
    def category(self) -> Literal["transient", "permanent", "terminal"]: ...
    @property
    def handler_message(self) -> str: ...

class ResponseTimeoutError(ResponseError): ...
class ResponseFormatMismatchError(ResponseError): ...
class MalformedResponseError(ResponseError): ...

RequestResult: TypeAlias = T | ResponseError
