import enum
from typing import Generic, List, Optional, Tuple, Union, overload

from typing_extensions import TypeVar, Unpack

from prosody.definition import (
    DequeDefinition as DequeDefinition,
    MapDefinition as MapDefinition,
    MessageDequeDefinition as MessageDequeDefinition,
    MessageMapDefinition as MessageMapDefinition,
    MessageValueDefinition as MessageValueDefinition,
    D_co as D_co,
    P as P,
    ReadCache as ReadCache,
    SetDefinition as SetDefinition,
    ValueDefinition as ValueDefinition,
    _StateConfig as _StateConfig,
    deque as deque,
    map as map,
    message_deque as message_deque,
    message_map as message_map,
    message_value as message_value,
    set as set,
    value as value,
)
from prosody.message import JSONInput, JSONValue
from prosody.published import (
    PublishedDeque as PublishedDeque,
    PublishedMap as PublishedMap,
    PublishedSet as PublishedSet,
    PublishedValue as PublishedValue,
)
from prosody.query import (
    Direction as Direction,
    _KeyOptions,
    _PositionOptions,
    _StateScan as _StateScan,
)

# PEP 696 defaults: an unparameterized handle uses ``JSONValue``.
T = TypeVar("T", default=JSONValue)  # value / deque item type
V = TypeVar("V", default=JSONValue)  # map value type
D = TypeVar("D")  # get() default's own type, preserved in the return


class StoreOutcome(enum.Enum):
    APPLIED = "applied"
    NO_OP = "no_op"


class ValueState(Generic[T]):
    async def get(self) -> Optional[T]: ...
    @overload
    async def set(self: "ValueState[JSONValue]", value: JSONInput) -> None: ...
    @overload
    async def set(self, value: T) -> None: ...
    async def clear(self) -> None: ...
    async def commit(self) -> StoreOutcome: ...
    async def rollback(self) -> StoreOutcome: ...


class MapState(Generic[V]):
    @overload
    async def get(self, key: str) -> Optional[V]: ...
    @overload
    async def get(self, key: str, default: D) -> Union[V, D]: ...
    async def contains(self, key: str) -> bool: ...
    async def get_many(self, keys: List[str]) -> List[Optional[V]]: ...
    async def contains_many(self, keys: List[str]) -> List[bool]: ...
    async def is_empty(self) -> bool: ...
    @overload
    async def set(self: "MapState[JSONValue]", key: str, value: JSONInput) -> None: ...
    @overload
    async def set(self, key: str, value: V) -> None: ...
    async def remove(self, key: str) -> None: ...
    async def clear(self) -> None: ...
    def items(
        self, direction: Direction = ..., **options: Unpack[_KeyOptions]
    ) -> _StateScan[Tuple[str, V]]: ...
    def keys(
        self, direction: Direction = ..., **options: Unpack[_KeyOptions]
    ) -> _StateScan[str]: ...
    def values(
        self, direction: Direction = ..., **options: Unpack[_KeyOptions]
    ) -> _StateScan[V]: ...
    def __aiter__(self) -> _StateScan[str]: ...
    async def commit(self) -> StoreOutcome: ...
    async def rollback(self) -> StoreOutcome: ...


class SetState:
    async def add(self, member: str) -> None: ...
    async def discard(self, member: str) -> None: ...
    async def contains(self, member: str) -> bool: ...
    async def contains_many(self, members: List[str]) -> List[bool]: ...
    async def is_empty(self) -> bool: ...
    async def clear(self) -> None: ...
    def members(
        self, direction: Direction = ..., **options: Unpack[_KeyOptions]
    ) -> _StateScan[str]: ...
    def __aiter__(self) -> _StateScan[str]: ...
    async def commit(self) -> StoreOutcome: ...
    async def rollback(self) -> StoreOutcome: ...


class DequeState(Generic[T]):
    @overload
    async def append(self: "DequeState[JSONValue]", item: JSONInput) -> None: ...
    @overload
    async def append(self, item: T) -> None: ...
    @overload
    async def appendleft(self: "DequeState[JSONValue]", item: JSONInput) -> None: ...
    @overload
    async def appendleft(self, item: T) -> None: ...
    async def pop(self) -> Optional[T]: ...
    async def popleft(self) -> Optional[T]: ...
    async def peek(self) -> Optional[T]: ...
    async def peekleft(self) -> Optional[T]: ...
    async def get(self, index: int) -> Optional[T]: ...
    async def size(self) -> int: ...
    async def is_empty(self) -> bool: ...
    async def clear(self) -> None: ...
    def values(
        self, direction: Direction = ..., **options: Unpack[_PositionOptions]
    ) -> _StateScan[T]: ...
    def __aiter__(self) -> _StateScan[T]: ...
    async def commit(self) -> StoreOutcome: ...
    async def rollback(self) -> StoreOutcome: ...
