[plan.work.ci]
paths = [".config/rail.toml", ".github/**"]
scope = "repository"

[plan.work.python]
paths = [
    "examples/**",
    "pyproject.toml",
    "pytest.ini",
    "python/**",
    "tests/**",
    "tox.ini",
]
scope = "repository"

[plan.work.taplo]
paths = [".taplo.toml", "pyproject.toml"]
scope = "repository"
